#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-httpcomponents-parent
Version  : 10
Release  : 1
URL      : https://github.com/apache/httpcomponents-parent/archive/10.tar.gz
Source0  : https://github.com/apache/httpcomponents-parent/archive/10.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-parent/10/httpcomponents-parent-10.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-httpcomponents-parent-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-httpcomponents-parent package.
Group: Data

%description data
data components for the mvn-httpcomponents-parent package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/httpcomponents/httpcomponents-parent/10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/httpcomponents/httpcomponents-parent/10


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/httpcomponents/httpcomponents-parent/10/httpcomponents-parent-10.pom
